adds custom database (default: postgres) and adds devise
koombea/generapp pull request #13
Opened 2017-03-31 20:49 UTC by jams1983

2017-03-31 21:14 UTC, miguelperez requested changes
Quizá cambiar la forma como esto está estructurado. Pq actualmente hay cosas que se meten a mano en el gemfile siendo que hay generators para ese tipo de cosas.

2017-03-31 21:14 UTC, miguelperez commented on lib/generapp/actions/devise.rb
> +        last_line = "config.file_watcher = ActiveSupport::EventedFileUpdateChecker\n"
creo que hay uno para meter `configs`. A menos que nos aseguremos que ese `last_line` siempre será la última línea.

2017-03-31 21:14 UTC, miguelperez commented on lib/generapp/generators/app_generator.rb
> +          Generapp::Actions::Devise.instance_methods(false).each do |action|
esto pq así?

2017-03-31 21:14 UTC, miguelperez commented on templates/Gemfile.erb
> +<% gemfile_entries.each do |gem| -%>
debe haber una forma mejor de hacer esto. quizá usando los generators para gems http://api.rubyonrails.org/classes/Rails/Generators/Actions.html

2017-03-31 21:14 UTC, miguelperez commented on templates/Gemfile.erb
> +<% gemfile_entries.each do |gem| -%>
Además me gustaría ver los tests y también me gustaría ver una entrada en el `README` donde se explica lo que se agrega de devise y lo que se corre.

2017-04-03 15:10 UTC, jams1983 commented on lib/generapp/actions/devise.rb
> +        last_line = "config.file_watcher = ActiveSupport::EventedFileUpdateChecker\n"
no hay un archivo para meter configs. el archivo configuration.rb mete cosas en el rakefile, setea la version y mete el procfile. development.rb escribe en el development.rb del proyecto pero hace otras cosas, y por esocree un archivo para devise, ademas que en caso que requiera agregar mas acciones que tengan que ver con devise las tengamos en un solo archivo.

2017-04-03 15:56 UTC, jams1983 commented on lib/generapp/actions/devise.rb
> +        last_line = "config.file_watcher = ActiveSupport::EventedFileUpdateChecker\n"
con respecto al last_line, le cambiaria el nombre, pero idea es usar una linea que me asegure que siempre va a estar como lo hacen con la configuracion de bullet

2018-02-20 16:15 UTC, closed without merging